const crypto = require("crypto");

/**
 * Fisher-Yates shuffle implementation.
 */
function shuffleArray(array) {
  const arr = [...array];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

/**
 * Normalizes correct answer representation to 0-indexed number (0, 1, 2, 3).
 */
function normalizeCorrectAnswerIndex(rawAnswer, options) {
  if (typeof rawAnswer === "number" && rawAnswer >= 0 && rawAnswer < options.length) {
    return Math.floor(rawAnswer);
  }

  if (typeof rawAnswer === "string") {
    const trimmed = rawAnswer.trim().toUpperCase();
    if (["A", "B", "C", "D"].includes(trimmed)) {
      return ["A", "B", "C", "D"].indexOf(trimmed);
    }
    if (["0", "1", "2", "3"].includes(trimmed)) {
      return parseInt(trimmed, 10);
    }
    // Match option text
    const foundIndex = options.findIndex(opt => opt.trim().toLowerCase() === rawAnswer.trim().toLowerCase());
    if (foundIndex !== -1) return foundIndex;
  }

  return 0; // fallback default
}

/**
 * Sanitizes invalid JSON escape sequences generated by LLMs.
 */
function cleanJSONString(str) {
  if (!str) return "";
  return str
    .replace(/[\u0000-\u001F]+/g, " ") // replace raw control characters with space
    .replace(/\\(?!["\\/bfnrtu])/g, "\\\\"); // fix unescaped backslashes
}

/**
 * Clean & extract JSON from raw AI text response.
 */
function extractRawJSON(rawText) {
  if (!rawText) throw new Error("Empty raw text provided to question parser.");

  let cleaned = rawText
    .replace(/```json/gi, "")
    .replace(/```/g, "")
    .trim();

  // Try parsing directly
  try {
    return JSON.parse(cleaned);
  } catch (e) {
    try {
      return JSON.parse(cleanJSONString(cleaned));
    } catch (e2) {
      // Attempt to extract array [ ... ]
      const arrayStart = cleaned.indexOf("[");
      const arrayEnd = cleaned.lastIndexOf("]");
      if (arrayStart !== -1 && arrayEnd > arrayStart) {
        const jsonArrayStr = cleaned.substring(arrayStart, arrayEnd + 1);
        try {
          return JSON.parse(jsonArrayStr);
        } catch (e3) {
          return JSON.parse(cleanJSONString(jsonArrayStr));
        }
      }

      // Attempt to extract object { ... }
      const objStart = cleaned.indexOf("{");
      const objEnd = cleaned.lastIndexOf("}");
      if (objStart !== -1 && objEnd > objStart) {
        const jsonObjStr = cleaned.substring(objStart, objEnd + 1);
        try {
          return JSON.parse(jsonObjStr);
        } catch (e4) {
          return JSON.parse(cleanJSONString(jsonObjStr));
        }
      }

      throw new Error("Could not extract valid JSON structure from AI output.");
    }
  }
}

/**
 * Parses, validates, shuffles options, shuffles questions, and hashes the generated paper.
 */
function parseAndProcessMCQs(rawText) {
  const parsedData = extractRawJSON(rawText);

  let rawQuestions = [];
  if (Array.isArray(parsedData)) {
    rawQuestions = parsedData;
  } else if (parsedData && Array.isArray(parsedData.questions)) {
    rawQuestions = parsedData.questions;
  } else {
    throw new Error("Parsed JSON does not contain a questions array.");
  }

  if (rawQuestions.length === 0) {
    throw new Error("Generated questions array is empty.");
  }

  const processedQuestions = [];
  const questionTextSet = new Set();

  for (let i = 0; i < rawQuestions.length; i++) {
    const q = rawQuestions[i];
    if (!q || typeof q !== "object") continue;

    const questionStr = String(q.question || "").trim();
    if (questionStr.length < 15) continue; // Skip truncated questions

    // Avoid duplicate questions in same paper
    const normalizedQuestion = questionStr.toLowerCase();
    if (questionTextSet.has(normalizedQuestion)) continue;
    questionTextSet.add(normalizedQuestion);

    // Validate options
    let rawOptions = Array.isArray(q.options) ? q.options.map(opt => String(opt || "").trim()) : [];
    if (rawOptions.length < 4) continue;
    rawOptions = rawOptions.slice(0, 4);

    // Ensure all 4 options are non-empty
    if (rawOptions.some(opt => !opt)) continue;

    // Determine correct option text before shuffling
    const origCorrectIndex = normalizeCorrectAnswerIndex(q.correctAnswer, rawOptions);
    const correctOptionText = rawOptions[origCorrectIndex] || rawOptions[0];

    // Fisher-Yates Shuffle Options
    const indexedOptions = rawOptions.map((optText, idx) => ({ text: optText, isCorrect: idx === origCorrectIndex }));
    const shuffledIndexed = shuffleArray(indexedOptions);

    const newOptions = shuffledIndexed.map(item => item.text);
    const newCorrectIndex = shuffledIndexed.findIndex(item => item.isCorrect);

    const explanation = String(q.explanation || `The correct answer is option ${newCorrectIndex + 1}.`).trim();

    processedQuestions.push({
      id: processedQuestions.length + 1,
      question: questionStr,
      options: newOptions,
      correctAnswer: newCorrectIndex,
      explanation
    });
  }

  if (processedQuestions.length === 0) {
    throw new Error("No valid questions passed validation checks.");
  }

  // Shuffle final question order
  const finalQuestions = shuffleArray(processedQuestions).map((q, idx) => ({
    ...q,
    id: idx + 1
  }));

  // Generate SHA256 Paper Hash
  const paperContent = finalQuestions.map(q => q.question + q.options.join("")).join("|");
  const paperHash = crypto.createHash("sha256").update(paperContent).digest("hex");

  return {
    questions: finalQuestions,
    questionCount: finalQuestions.length,
    paperHash
  };
}

module.exports = {
  parseAndProcessMCQs,
  extractRawJSON,
  shuffleArray
};
